### ISSUE TITLE
Java Code Convention

### ISSUE THREAD

**Issue by ghost** [SonicSlash/R4-Sorting#3]
http://www.oracle.com/technetwork/java/codeconventions-150003.pdf
1. Расставь пробелы между инструкциями и выражениями согласно рекомендациям и примерам файла. Например, вместо `for(int i=0; i<mas.length; i++)` должно быть `for (int i = 0; i < mas.length; i++)`
2. Расставить правильно отступы по коду согласно документу и его примерам
3. Названия некоторых методов не соответствуют правилам именования методов

**Comment by SonicSlash** [comment]
Пробелы это наверное не у меня, вроде все проверил норм...
отступ в if сделал как положено
названия методов сделал с маленькой буквы в начале и с большой 2 слово

**Comment by ghost** [comment]
- Смотри `public class Bubble{` пробела то не хватает. 
- Между методами нужно делать пустую строку

В коммитах, которые относятся к задачам, пиши номер задачи, например комментарий может быть таким `#3 Java Code Convention`
